var PLAN_DATA = {
 "source": "2027作業記録.xlsx",
 "sheet": "作業計画,進捗 (週管理)中央",
 "built_at": "2026-08-13 19:38",
 "weeks": [
  {
   "week_no": 32,
   "date": "8/8",
   "memo": null,
   "kabou": null,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": null,
   "sun_max": null,
   "leaf_m2": null,
   "leaf_plant": null,
   "density": null,
   "tekika": null
  },
  {
   "week_no": 33,
   "date": "8/15",
   "memo": "手灌水：軍手で水量調節、床土には極力水をかけない",
   "kabou": null,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": null,
   "sun_max": null,
   "leaf_m2": null,
   "leaf_plant": null,
   "density": null,
   "tekika": null
  },
  {
   "week_no": 34,
   "date": "8/22",
   "memo": "定植：浅植えは床土が見える程度、少し土を被るくらいがいい\nボビンの整理は広く狭くで、２つ隣に誘引する",
   "kabou": null,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": null,
   "sun_max": null,
   "leaf_m2": null,
   "leaf_plant": null,
   "density": null,
   "tekika": null
  },
  {
   "week_no": 35,
   "date": "8/29",
   "memo": "手潅水でベリマーク、トリコデソイル施用\n潅水チューブはここまでに設置",
   "kabou": null,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 17.8,
   "sun_max": 18.4,
   "leaf_m2": null,
   "leaf_plant": null,
   "density": 2.22,
   "tekika": null
  },
  {
   "week_no": 36,
   "date": "9/5",
   "memo": "1段に対して必要な光量3.3Mj\n1段に対して水0.4L/1MJ\nこの基準で管理する（カーテンの調節、水くれ量）\n葉カビに注意",
   "kabou": null,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 15.3,
   "sun_max": 21.4,
   "leaf_m2": null,
   "leaf_plant": null,
   "density": 2.22,
   "tekika": null
  },
  {
   "week_no": 37,
   "date": "9/12",
   "memo": "３段目開花の前に灌水＆追肥\n猛暑の場合は9月先から水かける\n低ければ9月下旬\n葉カビに注意\n黄化葉巻に注意",
   "kabou": 1,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 10.8,
   "sun_max": 15.7,
   "leaf_m2": null,
   "leaf_plant": null,
   "density": 2.22,
   "tekika": null
  },
  {
   "week_no": 38,
   "date": "9/19",
   "memo": "猛暑日ホルモン処理は中2日以上開けてはならない\n畝マルチダクトは中旬までに設置し稼働\n葉カビに注意\n黄化葉巻に注意\nヨトウムシに注意",
   "kabou": 2,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 11.6,
   "sun_max": 21.4,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": null
  },
  {
   "week_no": 39,
   "date": "9/26",
   "memo": "この時期の摘葉は3枚づつとってよい\n8枚以下キープでよさそう\n葉カビに注意\n黄化葉巻に注意\nヨトウムシに注意",
   "kabou": 3,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 8.9,
   "sun_max": 15.2,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": 4
  },
  {
   "week_no": 40,
   "date": "10/3",
   "memo": "積算日射が10MJ/m2を割ったらトップリーフカット開始\n葉カビに注意\n黄化葉巻に注意\nヨトウムシに注意",
   "kabou": 4,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 9.3,
   "sun_max": 19.9,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": 4
  },
  {
   "week_no": 41,
   "date": "10/10",
   "memo": "１．２段目は裂果に注意、強めの摘葉で蒸散促進する\n葉カビに注意\n黄化葉巻に注意\nヨトウムシに注意",
   "kabou": 4,
   "temp_avg": 18,
   "temp_day": 22,
   "temp_night": 14,
   "temp_dif": 8,
   "sun_avg": 12.1,
   "sun_max": 19.7,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": 4
  },
  {
   "week_no": 42,
   "date": "10/17",
   "memo": "マルチ設置ここまでに終わらせる\n１．２段目は裂果に注意、強めの摘葉で蒸散促進する\n葉カビに注意\n黄化葉巻に注意\nヨトウムシに注意",
   "kabou": 5,
   "temp_avg": 18,
   "temp_day": 22,
   "temp_night": 14,
   "temp_dif": 8,
   "sun_avg": 9.5,
   "sun_max": 14.8,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": 4
  },
  {
   "week_no": 43,
   "date": "10/24",
   "memo": "内張り展張サイドカーテン密閉\nCO2施用開始\n１．２段目は裂果に注意、強めの摘葉で蒸散促進する\n葉カビに注意\n黄化葉巻に注意\nヨトウムシに注意",
   "kabou": 6,
   "temp_avg": 17.5,
   "temp_day": 22,
   "temp_night": 14,
   "temp_dif": 8,
   "sun_avg": 7.9,
   "sun_max": 17.2,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": 4
  },
  {
   "week_no": 44,
   "date": "10/31",
   "memo": "摘果４→3\n5段目か場合によっては4段目には確実に実施\n葉カビに注意\n黄化葉巻に注意\nヨトウムシに注意",
   "kabou": 6,
   "temp_avg": 17.5,
   "temp_day": 22,
   "temp_night": 14,
   "temp_dif": 8,
   "sun_avg": 12.3,
   "sun_max": 16.6,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": 4
  },
  {
   "week_no": 45,
   "date": "11/7",
   "memo": "疫病に注意！！\n黄化葉巻に注意",
   "kabou": 7,
   "temp_avg": 17,
   "temp_day": 21,
   "temp_night": 14,
   "temp_dif": 7,
   "sun_avg": 8.7,
   "sun_max": 15.7,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": 3
  },
  {
   "week_no": 46,
   "date": "11/14",
   "memo": "疫病に注意！！\n黄化葉巻に注意",
   "kabou": 8,
   "temp_avg": 16.5,
   "temp_day": 20.5,
   "temp_night": 14,
   "temp_dif": 6.5,
   "sun_avg": 9,
   "sun_max": 14.8,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": 3
  },
  {
   "week_no": 47,
   "date": "11/21",
   "memo": "換気が閉まってきたらCO２は高濃度施用\n疫病に注意！！\n黄化葉巻に注意",
   "kabou": 8,
   "temp_avg": 16.5,
   "temp_day": 20,
   "temp_night": 14,
   "temp_dif": 6,
   "sun_avg": 10.7,
   "sun_max": 13.2,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": 3
  },
  {
   "week_no": 48,
   "date": "11/28",
   "memo": "年内にサビダニ予防をしておくこと\n葉枚数は最低に。6～7枚まで減らす\n疫病に注意！！\n黄化葉巻に注意",
   "kabou": 9,
   "temp_avg": 16.2,
   "temp_day": 20,
   "temp_night": 13.5,
   "temp_dif": 6.5,
   "sun_avg": 10.9,
   "sun_max": 12.4,
   "leaf_m2": 16,
   "leaf_plant": 7.2,
   "density": 2.22,
   "tekika": 3
  },
  {
   "week_no": 49,
   "date": "12/5",
   "memo": "日射量最低、地温も下がる、夜温下げ過ぎない、水やり過ぎない\n疫病に注意！！\n黄化葉巻に注意",
   "kabou": 9,
   "temp_avg": 16.2,
   "temp_day": 20,
   "temp_night": 13.5,
   "temp_dif": 6.5,
   "sun_avg": 9.7,
   "sun_max": 12.3,
   "leaf_m2": 16,
   "leaf_plant": 7.2,
   "density": 2.22,
   "tekika": 3
  },
  {
   "week_no": 50,
   "date": "12/12",
   "memo": "DIFよりも飽差優先\n日中はなるべく換気を開けるが２５℃はキープしたい\nチップバーンに注意",
   "kabou": 10,
   "temp_avg": 16.2,
   "temp_day": 20,
   "temp_night": 13.5,
   "temp_dif": 6.5,
   "sun_avg": 10.4,
   "sun_max": 11.3,
   "leaf_m2": 16,
   "leaf_plant": 7.2,
   "density": 2.22,
   "tekika": 3
  },
  {
   "week_no": 51,
   "date": "12/19",
   "memo": "日中温度下げ過ぎない、快晴なら25℃最高目標\n平均温度１６℃以上頑張る\nチップバーンに注意\n灰色カビ病に注意",
   "kabou": 10,
   "temp_avg": 16.2,
   "temp_day": 20,
   "temp_night": 13.5,
   "temp_dif": 6.5,
   "sun_avg": 10.5,
   "sun_max": 11.8,
   "leaf_m2": 16,
   "leaf_plant": 7.2,
   "density": 2.22,
   "tekika": 3
  },
  {
   "week_no": 52,
   "date": "12/26",
   "memo": "年始で作業遅れが出ないように、前倒しで作業実施する\n葉っぱは６枚以下でもよい\nチップバーンに注意\n灰色カビ病に注意",
   "kabou": 11,
   "temp_avg": 16.2,
   "temp_day": 20,
   "temp_night": 13.5,
   "temp_dif": 6.5,
   "sun_avg": 10.5,
   "sun_max": 11.8,
   "leaf_m2": 16,
   "leaf_plant": 7.2,
   "density": 2.22,
   "tekika": 3
  },
  {
   "week_no": 53,
   "date": "1/2",
   "memo": null,
   "kabou": 11,
   "temp_avg": 16.2,
   "temp_day": 20,
   "temp_night": 13.5,
   "temp_dif": 6.5,
   "sun_avg": 10.1,
   "sun_max": 11.7,
   "leaf_m2": 16,
   "leaf_plant": 7.2,
   "density": 2.22,
   "tekika": 3
  },
  {
   "week_no": 1,
   "date": "1/9",
   "memo": "増枝1回目25％まし\n柱間2本ずつ増枝\n年明けすぐ行う\nチップバーンに注意\n灰色カビ病に注意",
   "kabou": 12,
   "temp_avg": 16.2,
   "temp_day": 19.5,
   "temp_night": 13.5,
   "temp_dif": 6,
   "sun_avg": 11.3,
   "sun_max": 12.3,
   "leaf_m2": 18,
   "leaf_plant": 8.1,
   "density": 2.22,
   "tekika": 3
  },
  {
   "week_no": 2,
   "date": "1/16",
   "memo": "チップバーンに注意\n灰色カビ病に注意",
   "kabou": 12,
   "temp_avg": 16.2,
   "temp_day": 19.5,
   "temp_night": 13.5,
   "temp_dif": 6,
   "sun_avg": 11.1,
   "sun_max": 12.3,
   "leaf_m2": 22,
   "leaf_plant": 8.1,
   "density": 2.71,
   "tekika": 3
  },
  {
   "week_no": 3,
   "date": "1/23",
   "memo": "灌水量は増やす\n徐々に樹勢を強める管理に変更\nチップバーンに注意\n灰色カビ病に注意",
   "kabou": 13,
   "temp_avg": 16.2,
   "temp_day": 19.5,
   "temp_night": 13.5,
   "temp_dif": 6,
   "sun_avg": 12.9,
   "sun_max": 13.5,
   "leaf_m2": 22,
   "leaf_plant": 8.1,
   "density": 2.71,
   "tekika": 3
  },
  {
   "week_no": 4,
   "date": "1/30",
   "memo": "今シーズン、中央は摘果３つのまま走る\n東は４つにするかも\nチップバーンに注意\n灰色カビ病に注意",
   "kabou": 14,
   "temp_avg": 16.5,
   "temp_day": 19.5,
   "temp_night": 14,
   "temp_dif": 5.5,
   "sun_avg": 11.4,
   "sun_max": 13.7,
   "leaf_m2": 24,
   "leaf_plant": 8.9,
   "density": 2.71,
   "tekika": 3
  },
  {
   "week_no": 5,
   "date": "2/6",
   "memo": "葉っぱの枚数徐々に増やしていく、光量に合わせて調節\nチップバーンに注意\n灰色カビ病に要注意！！",
   "kabou": 14,
   "temp_avg": 17,
   "temp_day": 20,
   "temp_night": 14,
   "temp_dif": 6,
   "sun_avg": 14.8,
   "sun_max": 14.6,
   "leaf_m2": 26,
   "leaf_plant": 9.6,
   "density": 2.71,
   "tekika": 3
  },
  {
   "week_no": 6,
   "date": "2/13",
   "memo": "2月最終週で\n増枝20％、焦って前倒ししない、柱間2本増し\nチップバーンに注意\n灰色カビ病に要注意！！",
   "kabou": 15,
   "temp_avg": 17,
   "temp_day": 20,
   "temp_night": 14,
   "temp_dif": 6,
   "sun_avg": 14.6,
   "sun_max": 16.2,
   "leaf_m2": 26,
   "leaf_plant": 9.6,
   "density": 2.71,
   "tekika": 3
  },
  {
   "week_no": 7,
   "date": "2/20",
   "memo": "光量が急激に増えるので注意、灌水量UP、曇天日翌日は遮光を日中行う\nチップバーンに注意\n灰色カビ病に要注意！！",
   "kabou": 15,
   "temp_avg": 17.5,
   "temp_day": 20.5,
   "temp_night": 14.5,
   "temp_dif": 6,
   "sun_avg": 17.4,
   "sun_max": 17.6,
   "leaf_m2": 28,
   "leaf_plant": 10.3,
   "density": 2.71,
   "tekika": 3
  },
  {
   "week_no": 8,
   "date": "2/27",
   "memo": "トケル2号に切り替える（2月最終週では確実に）\nただし肥料切りすぎないように注意\nチップバーンに注意\n灰色カビ病に要注意！！",
   "kabou": 16,
   "temp_avg": 17.5,
   "temp_day": 20.5,
   "temp_night": 14.5,
   "temp_dif": 6,
   "sun_avg": 9.1,
   "sun_max": 18.6,
   "leaf_m2": 28,
   "leaf_plant": 10.3,
   "density": 2.71,
   "tekika": 3
  },
  {
   "week_no": 9,
   "date": "3/6",
   "memo": "しおれに細心の注意\n風予報みて換気コントロール\nトップリーフカット終了\n灰色カビ病注意",
   "kabou": 17,
   "temp_avg": 18,
   "temp_day": 21,
   "temp_night": 15,
   "temp_dif": 6,
   "sun_avg": 15.6,
   "sun_max": 19.6,
   "leaf_m2": 33,
   "leaf_plant": 10.1,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 10,
   "date": "3/13",
   "memo": "光量が急激に増えるので注意、灌水は週ごとに最大値に向け増やしていく\n灰色カビ病注意",
   "kabou": 17,
   "temp_avg": 18,
   "temp_day": 21,
   "temp_night": 15,
   "temp_dif": 6,
   "sun_avg": 17.2,
   "sun_max": 19.7,
   "leaf_m2": 33,
   "leaf_plant": 10.1,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 11,
   "date": "3/20",
   "memo": "サイドは内張りを下したまま外張りだけ開けて温度コントロール\n３月２０日過ぎるとしおれ要注意！\n遮光カーテン検討\n灰色カビ病注意",
   "kabou": 18,
   "temp_avg": 18,
   "temp_day": 21,
   "temp_night": 15,
   "temp_dif": 6,
   "sun_avg": 15,
   "sun_max": 19.9,
   "leaf_m2": 33,
   "leaf_plant": 10.1,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 12,
   "date": "3/27",
   "memo": "水多い、灰色カビ病要注意、逃げ切れるか重要ポイント\nしおれに要注意！！\n遮光カーテン検討",
   "kabou": 18,
   "temp_avg": 18.5,
   "temp_day": 21.5,
   "temp_night": 15,
   "temp_dif": 6.5,
   "sun_avg": 13.3,
   "sun_max": 22.5,
   "leaf_m2": 36,
   "leaf_plant": 11,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 13,
   "date": "4/3",
   "memo": "マグ欠に注意\nうどん粉の予防\nしおれに要注意！！\n遮光カーテンを使用",
   "kabou": 19,
   "temp_avg": 18.5,
   "temp_day": 21.5,
   "temp_night": 15,
   "temp_dif": 6.5,
   "sun_avg": 17.8,
   "sun_max": 23.2,
   "leaf_m2": 36,
   "leaf_plant": 11,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 14,
   "date": "4/10",
   "memo": "どれだけ日中下げられるかの勝負\nサイド開ける場合は風上は開けない\nしおれに要注意\n遮光カーテンを使用",
   "kabou": 19,
   "temp_avg": 18.5,
   "temp_day": 21.5,
   "temp_night": 15,
   "temp_dif": 6.5,
   "sun_avg": 18.2,
   "sun_max": 24.3,
   "leaf_m2": 40,
   "leaf_plant": 12.3,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 15,
   "date": "4/17",
   "memo": "葉枚数最大の１２枚以上キープ\n光に対してしっかり樹勢を付ける\nしおれに要注意！\n遮光カーテンを使用\n根コブセンチュウ注意",
   "kabou": 20,
   "temp_avg": 18.5,
   "temp_day": 21.5,
   "temp_night": 15,
   "temp_dif": 6.5,
   "sun_avg": 15.6,
   "sun_max": 26.1,
   "leaf_m2": 40,
   "leaf_plant": 12.3,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 16,
   "date": "4/24",
   "memo": "GWで作業遅れが出ないように前倒しで作業実施\n気温によってはサイドカーテン全開\n根コブセンチュウ注意",
   "kabou": 20,
   "temp_avg": 19,
   "temp_day": 21.5,
   "temp_night": 15,
   "temp_dif": 6.5,
   "sun_avg": 21.7,
   "sun_max": 26.1,
   "leaf_m2": 40,
   "leaf_plant": 12.3,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 17,
   "date": "5/1",
   "memo": "ここまでにうどん粉予防の消毒を行う\n消毒最終日には遮熱材塗布を行う\n青枯れ病要注意\n根コブセンチュウ注意",
   "kabou": 21,
   "temp_avg": 19,
   "temp_day": 21.5,
   "temp_night": 15,
   "temp_dif": 6.5,
   "sun_avg": 17.3,
   "sun_max": 28.7,
   "leaf_m2": 40,
   "leaf_plant": 12.3,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 18,
   "date": "5/8",
   "memo": "サイドカーテンあける→灌水最大\n田植え、作業遅れ注意\n青枯れ病要注意\n根コブセンチュウ注意",
   "kabou": 21,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 18.1,
   "sun_max": 28.3,
   "leaf_m2": 40,
   "leaf_plant": 12.3,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 19,
   "date": "5/15",
   "memo": "サイドカーテン全開でCO2施用終了\n夜寒い日が来たらめんどくさがらずに夜間サイドカーテン降ろす！\n青枯れ病要注意\n根コブセンチュウ注意\nうどん粉病注意",
   "kabou": 22,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 15.7,
   "sun_max": 29,
   "leaf_m2": 40,
   "leaf_plant": 12.3,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 20,
   "date": "5/22",
   "memo": "西と南は摘心を終わらせておく\n青枯れ病要注意\n根コブセンチュウ注意\nうどん粉病注意",
   "kabou": 23,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 12.6,
   "sun_max": 29.1,
   "leaf_m2": 40,
   "leaf_plant": 12.3,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 21,
   "date": "5/29",
   "memo": "青枯れ病要注意\n根コブセンチュウ注意\nうどん粉病注意",
   "kabou": 7,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 20.1,
   "sun_max": 28.7,
   "leaf_m2": 40,
   "leaf_plant": 12.3,
   "density": 3.26,
   "tekika": 3
  },
  {
   "week_no": 22,
   "date": "6/5",
   "memo": "中央東芯止めは6月入ってからが理想だが作業遅れないことも大事\nなるべく小さい芽で摘んだ方がいい\n青枯れ病要注意\n根コブセンチュウ注意\nうどん粉病注意",
   "kabou": 6,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 10.9,
   "sun_max": 24,
   "leaf_m2": 40,
   "leaf_plant": 12.3,
   "density": 3.26,
   "tekika": null
  },
  {
   "week_no": 23,
   "date": "6/12",
   "memo": "青枯れ病要注意\n根コブセンチュウ注意\nうどん粉病注意\n※西と南は病気はもう気にしない",
   "kabou": 5,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 21.1,
   "sun_max": 29.6,
   "leaf_m2": 38,
   "leaf_plant": 11.7,
   "density": 3.26,
   "tekika": null
  },
  {
   "week_no": 24,
   "date": "6/19",
   "memo": "爆発に備えて作業は終わらせておく\nここからは基本収穫しかできない\n※病気はもう気にしない",
   "kabou": 4,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 16.9,
   "sun_max": 29.7,
   "leaf_m2": 38,
   "leaf_plant": 11.7,
   "density": 3.26,
   "tekika": null
  },
  {
   "week_no": 25,
   "date": "6/26",
   "memo": "追肥終了検討\n西と南は収穫終了\n日中快晴時は遮光カーテンをすること、実が焼ける",
   "kabou": 3,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 16.9,
   "sun_max": 25.6,
   "leaf_m2": 34,
   "leaf_plant": 9,
   "density": 3.26,
   "tekika": null
  },
  {
   "week_no": 26,
   "date": "7/3",
   "memo": "日中快晴時は遮光カーテンをすること、実が焼ける",
   "kabou": 2,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": 14.1,
   "sun_max": 20.2,
   "leaf_m2": 34,
   "leaf_plant": 6,
   "density": 3.26,
   "tekika": null
  },
  {
   "week_no": 27,
   "date": "7/10",
   "memo": "収穫終了",
   "kabou": 1,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": null,
   "sun_max": null,
   "leaf_m2": null,
   "leaf_plant": 3,
   "density": 3.26,
   "tekika": null
  },
  {
   "week_no": 28,
   "date": "7/17",
   "memo": null,
   "kabou": null,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": null,
   "sun_max": null,
   "leaf_m2": null,
   "leaf_plant": null,
   "density": 3.26,
   "tekika": null
  },
  {
   "week_no": 29,
   "date": "7/24",
   "memo": null,
   "kabou": null,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": null,
   "sun_max": null,
   "leaf_m2": null,
   "leaf_plant": null,
   "density": 3.26,
   "tekika": null
  },
  {
   "week_no": 30,
   "date": "7/31",
   "memo": null,
   "kabou": null,
   "temp_avg": null,
   "temp_day": null,
   "temp_night": null,
   "temp_dif": null,
   "sun_avg": null,
   "sun_max": null,
   "leaf_m2": null,
   "leaf_plant": null,
   "density": 3.26,
   "tekika": null
  }
 ]
};
